<?xml version="1.0" encoding="utf-8"?><Database Name="Myregistration" Class="MyregClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-5ELMUM9\SQLEXPRESS;Initial Catalog=Myregistration;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Myregistre" Member="Myregistres">
    <Type Name="Myregistre">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MathAnaliz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Matlab" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Kirmex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>